/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.airline.service.flights.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import co.com.airline.service.flights.model.RequestflightReserve;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;

@CrossOrigin(origins="*")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-20T10:26:52.785-05:00[America/Bogota]")
@Api(value = "clientflight", description = "the client flights API")
public interface ClientFlightApi {


    @RequestMapping(value = "/client-flights/{identification}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> getFlightsById(@ApiParam(value = "User Identification",required=true) @PathVariable("identification") String identification);

    @RequestMapping(value = "/client-reserve",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> saveReserveFlight(@ApiParam(value = "request body save reserve" ,required=true )  @Valid @RequestBody RequestflightReserve body);
}
